config/routes.rb
Rails.application.routes.draw do

  get 'teachers_certifications/create'
  get 'teachers_certifications/destroy'
  get 'teachers/new_profile'
  get 'teachers/save_profile'
  get 'users/complete_profile'
  get 'users/update_profile'
  get 'messages/index'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'pages#home'

  get 'hubs/index'
  get 'hubs/show'
  get "profile/:id", to: "pages#profile", as: "profile"
  get "complete_profile", to: "users#complete_profile", as: "complete_profile"
  patch "complete_profile", to: "users#complete_profile"
  patch "update_profile", to: "users#update_profile", as: "update_profile"
  get "new_profile", to: "teachers#new_profile", as: "new_teacher_profile"
  post "save", to: "teachers#save_profile", as: "save_teacher_profile"
  post "friend/:id", to: "pages#request_friend", as: "request_friend"
  post "friends/:id", to: "pages#accept_friend", as: "accept_friend"
  delete "friend/:id", to: "pages#remove_friend", as: "remove_friend"
  delete "friend/:id", to: "pages#decline_request", as: "decline_request"
  get "dashboard", to: "pages#dashboard", as: 'dashboard'
  get "new_hub", to: "pages#current_hub"
  get "add_tag", to: "pages#add_tag"
  delete "remove_tag", to: "pages#remove_tag"

  resources :user_connections do
    resources :messages, only: [:index, :create,:new]
  end

  resources :events, only: [:edit, :destroy, :update, :show] do
    resources :event_bookings, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hubs, only: [:index, :show] do
    resources :events, only: :create
  end


  resources :teacher_certifications, only: [:create, :destroy]
  resources :teacher_teaching_styles, only: [:create, :destroy]
  resources :teacher_experiences, only: [:create, :update, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # bypass hub_id upon signup
  belongs_to :hub, optional: true
  has_many :event_bookings
  has_many :events, through: :event_bookings
  has_many :relationships, as: :tagable
  has_many :tags, through: :relationships
  has_many :teacher_experiences
  has_many :teacher_certifications
  has_many :teacher_languages
  has_many :teacher_teaching_styles
  validates :is_teacher, inclusion: { in: [true, false] }, on: :update
  validates :first_name, :last_name, :nationality, presence: true, on: :update
  has_many :user_connections
  has_many :messages, through: :user_connections
  # allows user to have - accept - and block friends
  has_friendship
  mount_uploader :profilephoto, PhotoUploader
  mount_uploader :coverphoto, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   raise
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    complete_profile_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def complete_profile
    @user = current_user
  end

  def update_profile
    @user = current_user

    if params[:save] == "save"
      params[:user][:tag_ids].shift
      params[:user][:tag_ids].each do |tagid|
        newtag = Tag.where(id: tagid)
        relation = Relationship.new(tag_id: newtag.first.id, tagable: @user)
        relation.save
      end
      redirect_to dashboard_path
    else
      if params[:save] == "save"
        params[:user][:tag_ids].shift
        params[:user][:tag_ids].each do |tagid|
          newtag = Tag.where(id: tagid)
          relation = Relationship.new(tag_id: newtag.first.id, tagable: @user)
          relation.save
        end
      end

      if @user.update(user_params)
        if @user.is_teacher
          redirect_to new_teacher_profile_path
        else
          redirect_to hubs_path({ :newhub => "newhub" })
        end
      else
        render 'complete_profile'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :birthdate, :nationality, :is_teacher, :profile_photo, :cover_photo)
  end
end

app/views/users/complete_profile.html.erb
<div class = "sign-up-body">
  <%= link_to root_path do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
  <div class="card card-signin p-5">
    <div class="text-center">
      <h1>Complete Your Profile</h1>
    </div>

    <%= simple_form_for @user, url: update_profile_path, method: :patch do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs onboarding">
        <%= f.input :first_name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "First Name" }%>
        <%= f.input :last_name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "Last Name" }%>
        <%= f.country_select :nationality,
                    label: "Country",
                    input_html: { class: "select2" } %>
        <%= f.input :is_teacher,
                    as: :boolean,
                    label: "Are you a teacher?",
                    required: true,
                    autofocus: true,
                    class: "pt-5",
                    input_html: { autocomplete: "teacher" } %>
        <%= f.input :description,
                    as: :text,
                    label: "Bio (optional)",
                    autofocus: true,
                    input_html: { autocomplete: "bio" }%>
        <%= f.input :profilephoto,
                    label: "Profile Photo (optional)",
                    autofocus: true,
                    input_html: { autocomplete: "photo" }%>
        <%= f.input :coverphoto,
                    label: "Cover Photo (optional)",
                    autofocus: true,
                    input_html: { autocomplete: "photo" }%>
        <fieldset class="form-group">
          <legend class="col-form-label pt-0">Interests (optional)</legend>
          <input type="hidden" name="user[tag_ids][]" value="">
          <div class="cards">
            <% Tag.all.where(tag_type: "user").each do |tag| %>
              <input class="hidden" style="display:none" type="checkbox" value="<%= tag.id %>" name="user[tag_ids][]" id="user_tag_ids_<%= tag.id %>">
              <label class="category-choice" for="user_tag_ids_<%= tag.id %>">
                <%= tag.tag_name %>
              </label>
            <% end %>
          </div>
        </fieldset>
      </div>
      <div class="justify-content-center text-center mx-auto">
        <%= f.submit "Save", class: "btn-md-blue justify-content-center text-center mx-auto" %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag "category_choice" %>

app/views/users/update_profile.html.erb
<h1>Users#update_profile</h1>
<p>Find me in app/views/users/update_profile.html.erb</p>