config/routes.rb
Rails.application.routes.draw do

  get 'teachers_certifications/create'
  get 'teachers_certifications/destroy'
  get 'teachers/new_profile'
  get 'teachers/save_profile'
  get 'users/complete_profile'
  get 'users/update_profile'
  get 'messages/index'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'pages#home'

  get 'hubs/index'
  get 'hubs/show'
  get "profile/:id", to: "pages#profile", as: "profile"
  get "complete_profile", to: "users#complete_profile", as: "complete_profile"
  patch "complete_profile", to: "users#complete_profile"
  patch "update_profile", to: "users#update_profile", as: "update_profile"
  get "new_profile", to: "teachers#new_profile", as: "new_teacher_profile"
  post "save", to: "teachers#save_profile", as: "save_teacher_profile"
  post "friend/:id", to: "pages#request_friend", as: "request_friend"
  post "friends/:id", to: "pages#accept_friend", as: "accept_friend"
  delete "friend/:id", to: "pages#remove_friend", as: "remove_friend"
  delete "friend/:id", to: "pages#decline_request", as: "decline_request"
  get "dashboard", to: "pages#dashboard", as: 'dashboard'
  get "new_hub", to: "pages#current_hub"
  get "add_tag", to: "pages#add_tag"
  delete "remove_tag", to: "pages#remove_tag"

  resources :user_connections do
    resources :messages, only: [:index, :create,:new]
  end

  resources :events, only: [:edit, :destroy, :update, :show] do
    resources :event_bookings, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hubs, only: [:index, :show] do
    resources :events, only: :create
  end


  resources :teacher_certifications, only: [:create, :destroy]
  resources :teacher_teaching_styles, only: [:create, :destroy]
  resources :teacher_experiences, only: [:create, :update, :destroy]


end

app/views/shared/_footer.html.erb
<footer class="page-footer font-small pt-4" id="sticky-footer" >
  <div class="container-fluid text-center">
    <div class="row d-flex justify-content-around align-items-center">
       <div class="col-md-4 mb-md-0 mb-3">
         <h5 class="text-uppercase">About</h5>
         <h5 class="text-uppercase">FAQ</h5>
         <h5 class="text-uppercase">Meet the Team</h5>
       </div>
       <hr class="clearfix w-100 d-md-none pb-3">
       <div class="col-md-4 mb-md-0 mb-3">
         <div class = "footer-link-logo">
            <%= link_to "#", class: "footer-img" do %>
            <%= image_tag "omline_name_logo.png", :width => 120%>
            <% end %>
          <div class="footer-links">
          <br>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>
        </div>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-4 mb-md-0 mb-3">
        <div class = "container mx-auto contact-info">
          <div>
            <div class="contact-info-items">
            <p><%= image_tag "address_icon.png", :width => 30 %> &nbsp;Jl. Munduk Catu No.32,<br> Canggu, Kuta Utara, Bali 80361</p>
          </div>
          <div class="contact-info-items">
            <p><%= image_tag "phone_icon.png", :width => 30 %> &nbsp;+1-234-567-8910</p>
          </div>
          <div class="contact-info-items">
            <p><%= image_tag "email_icon.png", :width => 30 %> &nbsp;support@omline.com</p>
          </div>

          </div>


        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-2">
    © OMline 2019 &nbsp;| &nbsp;Terms & Conditions
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "omline_logo.png" %>
  <% end %>

<% if user_signed_in? %>
  <div class="logout">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <div class = "navbar-icons">
          <li class="nav-bar nav-item active">
          <% if current_user.hub.nil? %>
            <%= link_to hubs_path, class: "nav-link" do%>
              <%= image_tag "home_icon.png", :width => 33 %>
            <% end %>
          <% else %>
            <%= link_to hub_path(current_user.hub.id), class: "nav-link" do%>
              <%= image_tag "home_icon.png", :width => 33 %>
            <% end %>
          <% end %>
          </li>
          <li class="nav-bar nav-item">
            <%= link_to hubs_path, class: "search nav-link" do%>
            <%= image_tag "search_icon.png", :width => 31 %>
            <% end %>
          </li>
          <li class="nav-bar nav-item">
              <% if @connections.present? %>
                <% if user_signed_in? %>
                <% counter = 0 %>
                <% UserConnection.where('connector_id = ? OR connectee_id = ?', current_user.id, current_user.id).each do |connection| %>
                  <% if Message.where(user_connection_id: connection.id).where.not(user_id: current_user.id).where(read: false).length > 0 %>
                    <% counter += Message.where(user_connection_id: connection.id).where.not(user_id: current_user.id).where(read: false).length %>
                  <% end %>
                <% end %>
                  <% if counter > 0  %>
                    <div class="notification-badge">
                      <i class="fas fa-circle"></i>
                      <p id="badge-count"><%= counter %></p>
                    </div>
                  <% end %>
                <% end %>
                <%= link_to user_connection_messages_path(@connections.first), class: "nav-link" do%>
                  <%= image_tag "message_icon.png", :width => 32 %>
                <% end %>
              <% elsif %>
                <%= link_to "#", class: "nav-link" do%>

                <%= image_tag "message_icon.png", :width => 32 %>
                <% end %>
              <% end %>
          </li>
        </div>
        <li class="nav-bar nav-item dropdown">
          <% if current_user.profilephoto.blank? %>
            <%= cl_image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.profilephoto, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu/-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <% else %>
    <div class="login d-flex justify-content-between">
      <%= link_to "Sign Up", new_user_registration_path, class:"nav-link btn-sm-white mr-3" %>
      <%= link_to "Login", user_session_path , class:"nav-link btn-sm-white" %>
    </div>
  <% end %>
</div>