config/routes.rb
Rails.application.routes.draw do

  get 'teachers_certifications/create'
  get 'teachers_certifications/destroy'
  get 'teachers/new_profile'
  get 'teachers/save_profile'
  get 'users/complete_profile'
  get 'users/update_profile'
  get 'messages/index'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'pages#home'

  get 'hubs/index'
  get 'hubs/show'
  get "profile/:id", to: "pages#profile", as: "profile"
  get "complete_profile", to: "users#complete_profile", as: "complete_profile"
  patch "complete_profile", to: "users#complete_profile"
  patch "update_profile", to: "users#update_profile", as: "update_profile"
  get "new_profile", to: "teachers#new_profile", as: "new_teacher_profile"
  post "save", to: "teachers#save_profile", as: "save_teacher_profile"
  post "friend/:id", to: "pages#request_friend", as: "request_friend"
  post "friends/:id", to: "pages#accept_friend", as: "accept_friend"
  delete "friend/:id", to: "pages#remove_friend", as: "remove_friend"
  delete "friend/:id", to: "pages#decline_request", as: "decline_request"
  get "dashboard", to: "pages#dashboard", as: 'dashboard'
  get "new_hub", to: "pages#current_hub"
  get "add_tag", to: "pages#add_tag"
  delete "remove_tag", to: "pages#remove_tag"

  resources :user_connections do
    resources :messages, only: [:index, :create,:new]
  end

  resources :events, only: [:edit, :destroy, :update, :show] do
    resources :event_bookings, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hubs, only: [:index, :show] do
    resources :events, only: :create
  end


  resources :teacher_certifications, only: [:create, :destroy]
  resources :teacher_teaching_styles, only: [:create, :destroy]
  resources :teacher_experiences, only: [:create, :update, :destroy]


end

app/models/hub.rb
class Hub < ApplicationRecord
  has_many :tags, as: :tagable
  has_many :events

  validates :city, presence: true
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  def index
    @search = params[:search]
    if @search.present?
      sql_query = "city ILIKE :search OR name ILIKE :search"
      @hubs = Hub.where(sql_query, search: "%#{@search}%")
    else
      @hubs = Hub.all
    end
  end

  def show
    @studios = Studio.geocoded #returns studios with coordinates
    @hub = Hub.find(params[:id])
    @cevents = @hub.events.group_by { |e| e.start_time.to_date }
    @event = Event.new
    @studios = Studio.where(hub: @hub)
    @users = User.where(hub: @hub)
    @markers = @studios.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { studio: studio }),
        image_url: helpers.asset_url("lotus_icon.png")
      }
    end
  end
end

app/views/hubs/_info_window.html.erb
<h5><%= studio.name %></h5>
<p><%= studio.address %>
<%= studio.website %>
<%= studio.email %>
<%= studio.phone_number %></p>

app/views/hubs/index.html.erb
<% if params[:newhub] == "newhub" %>
  <h2 class="container border-bottom text-center mb-3 pb-3 mt-4">Please Select a Destination</h2>
  <div class="hub-search py-2">
  <div class="hub-search-first py-2 mx-auto text-center">
    <%= form_tag hubs_path, method: :get do %>
      <%= text_field_tag :search,
        @search,
        class: "hub form-control",
        placeholder: "Search a location"
      %>
      <%= submit_tag "Search", class:"btn-sm-blue mx-auto"%>
    <% end %>
     </div>
  </div>

  <div class="hub-index cards container mb-5">
    <% @hubs.each do |hub|%>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= hub.photo %>)">
        <div class="col-md-9 text-center">
            <%= link_to hub.name, hub_path(hub.id)%>
            <h4><%= link_to hub.city, hub_path(hub.id)%></h4>
          <div class="row justify-content-center pt-2">
            <%= link_to "Select", new_hub_path({ :newhub => hub.id }), { :class=>"btn-md-blue" }%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>


<div class="card-category hubs-index" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://res.cloudinary.com/le-wagon1234/image/upload/v1573545509/capetown_med_mtxigo.jpg)">
  <h1 class="hubs-index-header">YOGA DESTINATIONS</h1>
    <div class="hub-search py-2">
    <div class="hub-search-first py-2 mx-auto text-center">
    <%= form_tag hubs_path, method: :get do %>
      <%= text_field_tag :search,
        @search,
        class: "hub form-control",
        placeholder: "Enter a location"
      %>
      <%= submit_tag "Search", class:"btn-sm-blue mx-auto"%>
    <% end %>
  </div>
  </div>
</div>


  <div class="hub-index card-button">
    <div class="hub-index cards container">
      <% @hubs.each do |hub|%>
        <%= link_to hub_path(hub.id), class: "hub-btn" do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= hub.photo %>)">
            <div class = "hub-card-text">
            <%= hub.name %>
            <div class="hub-name"><h4><%= hub.city %></h4></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/hubs/show.html.erb
<div class = "hub-container">
  <% if @hub.id == 1 %>
<div class="card-category hub-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/le-wagon1234/image/upload/v1573486560/DSC_1251_el4p4x.jpg)">
  <% else  %>
<div class="card-category hub-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/le-wagon1234/image/upload/v1573721859/1562057394_0.jpg_jyfimi.jpg)">
 <% end  %>
  <h1 class="hub-name-show"><%= @hub.name.upcase %>
  </h1>
</div>
<div class = "row">
  <div class = "hub-users-title"><h2>YOGIS<h2></div>
  <div class = "col-12">
    <div class="hub-profile-cards"><% @users.each do |user| %>
      <% if user != current_user %>
      <div class="contact-box center-version">
        <div class = "top-prof-card">
          <%= link_to profile_path(user) do %>
          <%= cl_image_tag user.profilephoto, crop: :limit, class:"avatar-profile" %>
          <% end %>
          </a>
          <h5 class="text-center m-b-xs mt-3"><%= user.first_name %>&nbsp<%= user.last_name %>
          </h5>
        </div>
        <div class="contact-box-footer">
          <div class="m-t-xs btn-group">
            <% unless current_user == user || user.requested_friends.include?(current_user) || user.friends.include?(current_user) %>
              <div class="connect-<%= user.id %>">
                <%= link_to "Connect", request_friend_path(user), class:"btn-sm-white", method: :post, remote: true %>
              </div>
            <% end %>
            <% if user.requested_friends.include?(current_user)%>
              <%= link_to "Pending", "#", class:"btn-sm-white"%>
            <% elsif user.friends.include?(current_user) %>
              <%= link_to "#", class:"btn-sm-connected-white" do %>
                <div class="d-flex">
                  <i class="fa fa-check icon" aria-hidden="true"></i>
                  <p id="word">  Connected </p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="hub-events card">
        <h2 class="hub-box-title text-center">EVENTS</h2>
        <div class="event-box-content">
          <% if @hub.events.empty? %>
            <h5>There are no events in this hub yet.</h5>
          <% else %>
            <% @cevents.sort.each do |date| %>
              <% if date[0] >= Date.today %>
                <h5 class="text-left" ><%= date[0].strftime("%A, %b %d") %></h5>
              <% end %>
              <% date[1].each do |event| %>
                <% if event.end_time >= DateTime.now %>
                  <div class="card-product">
                    <%= cl_image_tag event.photo %>
                    <div class="card-product-infos">
                      <h2><%= link_to event.title, event_path(event) %></h2>
                      <p><strong>Location:&nbsp;</strong><%= event.location_name %></p>
                      <p><%= event.start_time.to_date.strftime("%A, %b %d")%> at <%= event.start_time.strftime("%l:%M")%> - <%= event.end_time.strftime("%l:%M %p")%></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <button id="create-event-btn" type="button" class="btn-md-blue" data-toggle="modal" data-target="#exampleModal">
          Create Event
        </button>
        <span id="form-to-render" data-to-render="<%= @failed %>">
        </span>
        <!-- Modal -->
        <div class="modal fade rounded" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content" id="event-modal">
              <div class="container">
                <div class="modal-header">
                  <h3 class="modal-title" id="exampleModalLabel">Create an Event</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="container">

                    <%= simple_form_for [@hub, @event] do |f| %>
                      <%= f.input :title %>
                      <%= f.input :photo %>
                      <%= f.input :photo_cache, as: :hidden %>
                      <%= f.input :description %>
                      <%= f.input :address %>
                      <%= f.input :location_name, label: "Location Name" %>
                      <div class="row justify-content-between time">
                      <%= f.input :start_time, as: :string, type: :text, label: "Start Date & Time", wrapper_html: { class: "same-row" }  %>
                      <%= f.input :end_time, as: :string, type: :text, label: "End Date & Time", wrapper_html: { class: "same-row" }  %>
                      </div>
                      <div class="row justify-content-between time">
                      <%= f.input :price, wrapper_html: { class: "same-row" } %>
                      <%= f.input :capacity, inline_label: 'Yes, remember me', wrapper_html: { class: "same-row" } %>
                      </div>
                      <%= f.button :submit, :class => 'btn-md-blue mx-auto' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>






    <div class="col-md-4">
      <div class="studio-events card">
        <h2 class="studio-title-top text-center">STUDIOS</h2>
        <nav>
          <div class="studio-tabs">
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"><h5>List</h5></a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"><h5>Map</h5></a>
          </div>
          </div>
        </nav>
        <div class="studio-cards tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active studio-box-content" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <% @studios.each do |studio| %>




              <div class="info-card">
      <div class="front">
        <div class="card front-card" style="width: 20rem;">
          <image><%= cl_image_tag studio.photo, crop: :fill, class:"card-img-top"%>
          </image>
          <div class="studio-name-front card-body mx-auto">
            <h4 class="card-title"><%= studio.name %></h4>
          </div>
        </div>
      </div>
      <div class="back">
        <div class="card studio" style="width: 20rem;">
          <div class="back-card">
            <div class="back-card-body">
              <div class="back-card-title">
                <h4><%= studio.name %></h4>
                <p>Styles: <%= studio.styles %></p>
              </div>
              <div class="back-card-info">
                <p><%= image_tag "web_icon.png", :width => 15 %>&nbsp<%= studio.website %></p>
                <p><%= image_tag "phone_icon.png", :width => 15 %>&nbsp<%= studio.phone_number %></p>
                <p><%= image_tag "email_icon.png", :width => 15 %>&nbsp<%= studio.email %></p>
                <p><%= image_tag "time_icon.png", :width => 15 %>&nbsp<%= studio.hours %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
            </p><% end %>
          </div>
          <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <div id="map" style="width: 100%; height: 507px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
<%= javascript_pack_tag 'map.js' %>