config/routes.rb
Rails.application.routes.draw do

  get 'teachers_certifications/create'
  get 'teachers_certifications/destroy'
  get 'teachers/new_profile'
  get 'teachers/save_profile'
  get 'users/complete_profile'
  get 'users/update_profile'
  get 'messages/index'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'pages#home'

  get 'hubs/index'
  get 'hubs/show'
  get "profile/:id", to: "pages#profile", as: "profile"
  get "complete_profile", to: "users#complete_profile", as: "complete_profile"
  patch "complete_profile", to: "users#complete_profile"
  patch "update_profile", to: "users#update_profile", as: "update_profile"
  get "new_profile", to: "teachers#new_profile", as: "new_teacher_profile"
  post "save", to: "teachers#save_profile", as: "save_teacher_profile"
  post "friend/:id", to: "pages#request_friend", as: "request_friend"
  post "friends/:id", to: "pages#accept_friend", as: "accept_friend"
  delete "friend/:id", to: "pages#remove_friend", as: "remove_friend"
  delete "friend/:id", to: "pages#decline_request", as: "decline_request"
  get "dashboard", to: "pages#dashboard", as: 'dashboard'
  get "new_hub", to: "pages#current_hub"
  get "add_tag", to: "pages#add_tag"
  delete "remove_tag", to: "pages#remove_tag"

  resources :user_connections do
    resources :messages, only: [:index, :create,:new]
  end

  resources :events, only: [:edit, :destroy, :update, :show] do
    resources :event_bookings, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hubs, only: [:index, :show] do
    resources :events, only: :create
  end


  resources :teacher_certifications, only: [:create, :destroy]
  resources :teacher_teaching_styles, only: [:create, :destroy]
  resources :teacher_experiences, only: [:create, :update, :destroy]


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new_profile
  end

  def save_profile
    params[:teacher][:certifications].filter { |cert| cert != '' }.each do |id|
      TeacherCertification.create(certification_id: id, user: current_user)
    end

    params[:teacher][:styles].filter { |cert| cert != '' }.each do |id|
      TeacherTeachingStyle.create(teaching_style_id: id, user: current_user)
    end

    params[:teacher][:languages].filter { |cert| cert != '' }.each do |id|
      TeacherLanguage.create(language_id: id, user: current_user)
    end

     exp = params[:experience]

     size = exp["studio_name"].keys.count
     (0..size - 1).to_a.each do |index|
        TeacherExperience.create!(studio_name: exp[:studio_name][index.to_s], location: exp[:location][index.to_s], description: exp[:description][index.to_s], start_date: exp[:start_date][index.to_s], end_date: exp[:end_date][index.to_s], user: current_user)
     end

    redirect_to hubs_path
  end
end

app/views/teachers/new_profile.html.erb
<div class="teacher-container">
  <div class="card card-signin p-5">
    <%= simple_form_for :teacher, url: save_teacher_profile_path, method: :post do |f| %>

      <%= f.input :certifications, collection: Certification.all, as: :select, input_html: {class:'js-example-basic-multiple', multiple: true} %> <br>

      <hr>
      <%= f.input :styles, collection: TeachingStyle.all, as: :select, input_html: {class:'js-example-basic-multiple', multiple: true} %> <br>

      <hr>
      <%= f.input :languages, collection: Language.all, as: :select, input_html: {class:'js-example-basic-multiple', multiple: true} %> <br>

      <hr>
      <div id="experience-content">
        <div class="form-group string required teacher_studio_name">
          <label class="string required" for="teacher_studio_name">Studio name <abbr title="required">*</abbr></label>
          <input class="form-control string required" type="text" name="experience[studio_name][0]" id="teacher_studio_name">
        </div>
        <div class="form-group string required teacher_location">
          <label class="string required" for="teacher_location">Location <abbr title="required">*</abbr></label>
          <input class="form-control string required" type="text" name="experience[location][0]" id="teacher_location">
        </div>
        <div class="form-group string required teacher_description">
          <label class="string required" for="teacher_description">Description <abbr title="required">*</abbr></label>
          <input class="form-control string required" type="text" name="experience[description][0]" id="teacher_description">
        </div>
        <div class="form-group date required teacher_start_date">
          <label class="date required" for="teacher_start_date">Start date <abbr title="required">*</abbr></label>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <input class="form-control mx-1 date required" type="date" name="experience[start_date][0]" id="teacher_start_date">
          </div>
        </div>
        <div class="form-group date required teacher_end_date">
          <label class="date required" for="teacher_end_date">End date <abbr title="required">*</abbr></label>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <input class="form-control mx-1 date required" type="date" name="experience[end_date][0]" id="teacher_end_date">
          </div>
        </div>
      </div>
      <button id="add-experience" class="btn-md-blue">Add more</button>
      <div class="justify-content-center text-center mx-auto">
        <%= f.button :submit, "Save", class: "btn-md-blue justify-content-center text-center mx-auto" %>
      </div>
    <% end %>
  </div>
</div>

app/views/teachers/save_profile.html.erb
<h1>Teachers#save_profile</h1>
<p>Find me in app/views/teachers/save_profile.html.erb</p>